name: Playwright Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  E2E:
    env:
      EMAIL_SENDER_API_KEY: ${{ secrets.EMAIL_SENDER_API_KEY }}
      EMAIL_SENDER_FROM_EMAIL: ${{ secrets.EMAIL_SENDER_FROM_EMAIL }}
      EMAIL_SENDER_TO_EMAIL: ${{ secrets.EMAIL_SENDER_TO_EMAIL }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

        # Echo the environment variables for debugging
      - name: Echo environment variables
        run: |
          echo "EMAIL_SENDER_API_KEY: $EMAIL_SENDER_API_KEY"
          echo "EMAIL_SENDER_FROM_EMAIL: $EMAIL_SENDER_FROM_EMAIL"
          echo "EMAIL_SENDER_TO_EMAIL: $EMAIL_SENDER_TO_EMAIL"
          echo "NEXT_PUBLIC_BASE_URL: $NEXT_PUBLIC_BASE_URL"
      - name: Build the project
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
