name: Playwright Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  E2E:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      EMAIL_SENDER_API_KEY: ${{ secrets.EMAIL_SENDER_API_KEY }}
      EMAIL_SENDER_FROM_EMAIL: ${{ secrets.EMAIL_SENDER_FROM_EMAIL }}
      EMAIL_SENDER_TO_EMAIL: ${{ secrets.EMAIL_SENDER_TO_EMAIL }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build

      - name: Start the project
        run: npm run start &
        env:
          PORT: 3000
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
        continue-on-error: false
      - name: Wait for the server to start
        run: |
          echo "Waiting for the server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server to start..."
            sleep 5
          done
          if ! curl -s http://localhost:3000 > /dev/null; then
            echo "Server did not start in time!"
            exit 1
          fi

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
