name: Tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:unit

  e2e-tests:
    name: E2E Tests
    needs: unit-tests
    uses: ./.github/workflows/playwright.yml
    permissions:
      contents: read
      pull-requests: write
